services: 
  main_server: 
    build: 
      dockerfile: ./tests/dummy_controller.dockerfile 
    ports: 
      - "2222:22" # Maps port 22 in the container to port 2222 on the host
    networks: 
      - overlay_network 

  compute_node: 
    build: 
      dockerfile: ./tests/dummy_worker.dockerfile 
    deploy: 
      replicas: 1 # Increase number with --scale 
    ports: 
      - "6900-6942:22" # Maps port 22 in the container to port 6900-6942 on the host
    networks: 
      - overlay_network

networks: 
  overlay_network: 
    driver: bridge
